# Data Processing Tools
## Importing the libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

## Importing datasets

In [2]:
path="C:/Users/David/Desktop/Data Science and Machine Learning/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python"
os.listdir(path)

df1=pd.read_csv(path+'/Data.csv')
X = df1.iloc[:, :-1].values
y = df1.iloc[:, -1].values


## Taking care of missing data

In [3]:
##This is one way to get rid of missing data points, however when dealing with datasets that are small it is sometimes 
##better to replace that datapoint with an average.
#x=x.dropna(subset = ["Country","Age","Salary"], inplace=False)
#y=y.dropna(subset=["Purchased"], inplace=False)

##Another way is to use the pandas library method fillna to replace NaN in a dataset. 
##We will be using scikit learn to do this but it is always good to know standard methods  
#age_mean=x['Age'].mean()
#salary_mean=x['Salary'].mean()
#x['Age'].fillna(age_mean.round(),inplace=True)
#x['Salary'].fillna(salary_mean.round(),inplace=True)


from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])


In [4]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data
### Encoding the independant variable

In [5]:
#this will show one hot encoding
#we use one hot encoding to perform a “binarisation” of the category and include it as a feature to train the model.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

CT=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(CT.fit_transform(X, y=None))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the dependant variable

In [6]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
y=LE.fit_transform(y)

### Splitting the data into a training set and a testing set

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=1)


### Feature Scaling
##### Feature scaling is a method used to normalize the range of independent variables or features of data. In data processing, it is also known as data normalization and is generally performed during the data preprocessing step

In [8]:
from sklearn.preprocessing import StandardScaler
SSc=StandardScaler()
X_train[:, 3:] = SSc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = SSc.transform(X_test[:, 3:])